export const AUTH={
    UPDATE_EMAIL :"UPDATE_EMAIL",
    UPDATE_PASSWORD : "UPDATE_PASSWORD",
    UPDATE_LOGIN_INFO : "UPDATE_LOGIN_INFO",
    UPDATE_ROLL_TYPE : "UPDATE_ROLL_TYPE"
}

export const PRODUCT={
    UPDATE_PRODUCTS_LIST: "UPDATE_PRODUCTS_LIST",
    UPDATE_CATEGORY_LIST: "UPDATE_CATEGORY_LIST",
    UPDATE_CART_LIST: "UPDATE_CART_LIST",
    UPDATE_ORDER_HISTORY: "UPDATE_ORDER_HISTORY"
}


